# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mailer.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 941, 761))
        self.tabWidget.setObjectName("tabWidget")
        self.TabProp = QtWidgets.QWidget()
        self.TabProp.setAccessibleName("")
        self.TabProp.setObjectName("TabProp")
        self.textMail = QtWidgets.QTextEdit(self.TabProp)
        self.textMail.setGeometry(QtCore.QRect(10, 40, 701, 431))
        self.textMail.setObjectName("textMail")
        self.textSubject = QtWidgets.QLineEdit(self.TabProp)
        self.textSubject.setGeometry(QtCore.QRect(10, 10, 701, 21))
        self.textSubject.setObjectName("textSubject")
        self.tabWidget.addTab(self.TabProp, "")
        self.TabText = QtWidgets.QWidget()
        self.TabText.setObjectName("TabText")
        self.buttonSend = QtWidgets.QPushButton(self.TabText)
        self.buttonSend.setGeometry(QtCore.QRect(580, 40, 91, 81))
        self.buttonSend.setObjectName("buttonSend")
        self.groupSMTP = QtWidgets.QGroupBox(self.TabText)
        self.groupSMTP.setGeometry(QtCore.QRect(700, 0, 231, 191))
        self.groupSMTP.setFlat(False)
        self.groupSMTP.setCheckable(False)
        self.groupSMTP.setObjectName("groupSMTP")
        self.buttonTestSMTP = QtWidgets.QPushButton(self.groupSMTP)
        self.buttonTestSMTP.setGeometry(QtCore.QRect(130, 150, 91, 31))
        self.buttonTestSMTP.setObjectName("buttonTestSMTP")
        self.port = QtWidgets.QLineEdit(self.groupSMTP)
        self.port.setGeometry(QtCore.QRect(160, 30, 61, 21))
        self.port.setClearButtonEnabled(False)
        self.port.setObjectName("port")
        self.server = QtWidgets.QLineEdit(self.groupSMTP)
        self.server.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.server.setObjectName("server")
        self.name = QtWidgets.QLineEdit(self.groupSMTP)
        self.name.setGeometry(QtCore.QRect(10, 60, 211, 21))
        self.name.setText("")
        self.name.setClearButtonEnabled(True)
        self.name.setObjectName("name")
        self.password = QtWidgets.QLineEdit(self.groupSMTP)
        self.password.setGeometry(QtCore.QRect(10, 120, 211, 21))
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.username = QtWidgets.QLineEdit(self.groupSMTP)
        self.username.setGeometry(QtCore.QRect(10, 90, 211, 21))
        self.username.setText("")
        self.username.setClearButtonEnabled(True)
        self.username.setObjectName("username")
        self.groupDestination = QtWidgets.QGroupBox(self.TabText)
        self.groupDestination.setGeometry(QtCore.QRect(550, 190, 381, 531))
        self.groupDestination.setObjectName("groupDestination")
        self.buttonTo = QtWidgets.QPushButton(self.groupDestination)
        self.buttonTo.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.buttonTo.setObjectName("buttonTo")
        self.newEmail = QtWidgets.QLineEdit(self.groupDestination)
        self.newEmail.setGeometry(QtCore.QRect(10, 30, 361, 21))
        self.newEmail.setObjectName("newEmail")
        self.buttonCc = QtWidgets.QPushButton(self.groupDestination)
        self.buttonCc.setGeometry(QtCore.QRect(50, 50, 41, 21))
        self.buttonCc.setObjectName("buttonCc")
        self.buttonBcc = QtWidgets.QPushButton(self.groupDestination)
        self.buttonBcc.setGeometry(QtCore.QRect(90, 50, 41, 21))
        self.buttonBcc.setObjectName("buttonBcc")
        self.buttonRemove = QtWidgets.QPushButton(self.groupDestination)
        self.buttonRemove.setGeometry(QtCore.QRect(250, 500, 121, 21))
        self.buttonRemove.setObjectName("buttonRemove")
        self.treeDestination = QtWidgets.QTreeWidget(self.groupDestination)
        self.treeDestination.setGeometry(QtCore.QRect(10, 70, 361, 431))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.treeDestination.setFont(font)
        self.treeDestination.setAutoScrollMargin(12)
        self.treeDestination.setAlternatingRowColors(True)
        self.treeDestination.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeDestination.setRootIsDecorated(False)
        self.treeDestination.setUniformRowHeights(True)
        self.treeDestination.setHeaderHidden(False)
        self.treeDestination.setColumnCount(3)
        self.treeDestination.setObjectName("treeDestination")
        self.treeDestination.header().setMinimumSectionSize(20)
        self.treeDestination.header().setSortIndicatorShown(True)
        self.groupSource = QtWidgets.QGroupBox(self.TabText)
        self.groupSource.setGeometry(QtCore.QRect(10, 0, 531, 721))
        self.groupSource.setObjectName("groupSource")
        self.buttonSourceBcc = QtWidgets.QPushButton(self.groupSource)
        self.buttonSourceBcc.setGeometry(QtCore.QRect(480, 690, 41, 21))
        self.buttonSourceBcc.setObjectName("buttonSourceBcc")
        self.labelClass = QtWidgets.QLabel(self.groupSource)
        self.labelClass.setGeometry(QtCore.QRect(10, 100, 81, 18))
        self.labelClass.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClass.setObjectName("labelClass")
        self.buttonReadCharlemagne = QtWidgets.QPushButton(self.groupSource)
        self.buttonReadCharlemagne.setGeometry(QtCore.QRect(10, 40, 91, 31))
        self.buttonReadCharlemagne.setObjectName("buttonReadCharlemagne")
        self.buttonReadPersonnel = QtWidgets.QPushButton(self.groupSource)
        self.buttonReadPersonnel.setGeometry(QtCore.QRect(100, 40, 91, 31))
        self.buttonReadPersonnel.setObjectName("buttonReadPersonnel")
        self.labelEmails = QtWidgets.QLabel(self.groupSource)
        self.labelEmails.setGeometry(QtCore.QRect(90, 100, 301, 18))
        self.labelEmails.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEmails.setObjectName("labelEmails")
        self.buttonSourceTo = QtWidgets.QPushButton(self.groupSource)
        self.buttonSourceTo.setGeometry(QtCore.QRect(400, 690, 41, 21))
        self.buttonSourceTo.setObjectName("buttonSourceTo")
        self.buttonSourceCc = QtWidgets.QPushButton(self.groupSource)
        self.buttonSourceCc.setGeometry(QtCore.QRect(440, 690, 41, 21))
        self.buttonSourceCc.setObjectName("buttonSourceCc")
        self.listCategories = QtWidgets.QListWidget(self.groupSource)
        self.listCategories.setGeometry(QtCore.QRect(10, 120, 111, 571))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listCategories.setFont(font)
        self.listCategories.setAutoScrollMargin(12)
        self.listCategories.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listCategories.setObjectName("listCategories")
        self.treeSources = QtWidgets.QTreeWidget(self.groupSource)
        self.treeSources.setGeometry(QtCore.QRect(120, 120, 401, 571))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.treeSources.setFont(font)
        self.treeSources.setAutoScrollMargin(12)
        self.treeSources.setAlternatingRowColors(True)
        self.treeSources.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeSources.setRootIsDecorated(False)
        self.treeSources.setUniformRowHeights(True)
        self.treeSources.setHeaderHidden(False)
        self.treeSources.setColumnCount(3)
        self.treeSources.setObjectName("treeSources")
        self.treeSources.header().setDefaultSectionSize(100)
        self.treeSources.header().setMinimumSectionSize(20)
        self.treeSources.header().setSortIndicatorShown(False)
        self.buttonReadExported = QtWidgets.QPushButton(self.groupSource)
        self.buttonReadExported.setGeometry(QtCore.QRect(190, 40, 101, 31))
        self.buttonReadExported.setObjectName("buttonReadExported")
        self.buttonExport = QtWidgets.QPushButton(self.groupSource)
        self.buttonExport.setGeometry(QtCore.QRect(420, 40, 101, 31))
        self.buttonExport.setObjectName("buttonExport")
        self.tabWidget.addTab(self.TabText, "")
        self.logView = QtWidgets.QTextBrowser(self.centralwidget)
        self.logView.setGeometry(QtCore.QRect(950, 20, 411, 741))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.logView.setFont(font)
        self.logView.setAutoFillBackground(False)
        self.logView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logView.setObjectName("logView")
        self.labelLog = QtWidgets.QLabel(self.centralwidget)
        self.labelLog.setGeometry(QtCore.QRect(950, 0, 411, 20))
        self.labelLog.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLog.setObjectName("labelLog")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.textSubject)
        MainWindow.setTabOrder(self.textSubject, self.textMail)
        MainWindow.setTabOrder(self.textMail, self.newEmail)
        MainWindow.setTabOrder(self.newEmail, self.buttonTo)
        MainWindow.setTabOrder(self.buttonTo, self.buttonCc)
        MainWindow.setTabOrder(self.buttonCc, self.buttonBcc)
        MainWindow.setTabOrder(self.buttonBcc, self.server)
        MainWindow.setTabOrder(self.server, self.port)
        MainWindow.setTabOrder(self.port, self.name)
        MainWindow.setTabOrder(self.name, self.username)
        MainWindow.setTabOrder(self.username, self.password)
        MainWindow.setTabOrder(self.password, self.buttonTestSMTP)
        MainWindow.setTabOrder(self.buttonTestSMTP, self.buttonRemove)
        MainWindow.setTabOrder(self.buttonRemove, self.logView)
        MainWindow.setTabOrder(self.logView, self.buttonSend)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mass Mailer"))
        self.textMail.setPlaceholderText(_translate("MainWindow", "Enter the mail text here..."))
        self.textSubject.setPlaceholderText(_translate("MainWindow", "Enter the subject here..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabProp), _translate("MainWindow", "Mail Text"))
        self.buttonSend.setText(_translate("MainWindow", "Send \n"
"Emails"))
        self.groupSMTP.setTitle(_translate("MainWindow", "SMTP Information"))
        self.buttonTestSMTP.setText(_translate("MainWindow", "Test SMTP"))
        self.port.setText(_translate("MainWindow", "587"))
        self.port.setPlaceholderText(_translate("MainWindow", "Port"))
        self.server.setText(_translate("MainWindow", "smtp.gmail.com"))
        self.server.setPlaceholderText(_translate("MainWindow", "SMTP server"))
        self.name.setPlaceholderText(_translate("MainWindow", "Enter the real name"))
        self.password.setPlaceholderText(_translate("MainWindow", "Enter your password."))
        self.username.setPlaceholderText(_translate("MainWindow", "Enter the username."))
        self.groupDestination.setTitle(_translate("MainWindow", "Destination"))
        self.buttonTo.setText(_translate("MainWindow", "To"))
        self.newEmail.setPlaceholderText(_translate("MainWindow", "Add comma seperated emails."))
        self.buttonCc.setText(_translate("MainWindow", "Cc"))
        self.buttonBcc.setText(_translate("MainWindow", "Bcc"))
        self.buttonRemove.setText(_translate("MainWindow", "Remove Selected"))
        self.treeDestination.setSortingEnabled(True)
        self.treeDestination.headerItem().setText(0, _translate("MainWindow", "Email"))
        self.treeDestination.headerItem().setText(1, _translate("MainWindow", "Name"))
        self.treeDestination.headerItem().setText(2, _translate("MainWindow", "Mode"))
        self.groupSource.setTitle(_translate("MainWindow", "Sources"))
        self.buttonSourceBcc.setText(_translate("MainWindow", "Bcc"))
        self.labelClass.setText(_translate("MainWindow", "Categories"))
        self.buttonReadCharlemagne.setText(_translate("MainWindow", "Charlemagne"))
        self.buttonReadPersonnel.setText(_translate("MainWindow", "Personnel"))
        self.labelEmails.setText(_translate("MainWindow", "Emails"))
        self.buttonSourceTo.setText(_translate("MainWindow", "To"))
        self.buttonSourceCc.setText(_translate("MainWindow", "Cc"))
        self.treeSources.headerItem().setText(0, _translate("MainWindow", "Email"))
        self.treeSources.headerItem().setText(1, _translate("MainWindow", "Name"))
        self.treeSources.headerItem().setText(2, _translate("MainWindow", "Categories"))
        self.buttonReadExported.setText(_translate("MainWindow", "Read Exported"))
        self.buttonExport.setText(_translate("MainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabText), _translate("MainWindow", "Properties"))
        self.labelLog.setText(_translate("MainWindow", "System Log"))

