# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mailer.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 681, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.TabProp = QtWidgets.QWidget()
        self.TabProp.setAccessibleName("")
        self.TabProp.setObjectName("TabProp")
        self.textMail = QtWidgets.QTextEdit(self.TabProp)
        self.textMail.setGeometry(QtCore.QRect(10, 40, 651, 451))
        self.textMail.setObjectName("textMail")
        self.textSubject = QtWidgets.QLineEdit(self.TabProp)
        self.textSubject.setGeometry(QtCore.QRect(10, 10, 651, 21))
        self.textSubject.setObjectName("textSubject")
        self.tabWidget.addTab(self.TabProp, "")
        self.TabText = QtWidgets.QWidget()
        self.TabText.setObjectName("TabText")
        self.username = QtWidgets.QLineEdit(self.TabText)
        self.username.setGeometry(QtCore.QRect(460, 70, 211, 21))
        self.username.setText("")
        self.username.setClearButtonEnabled(True)
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.TabText)
        self.password.setGeometry(QtCore.QRect(460, 100, 211, 21))
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.buttonTestSMTP = QtWidgets.QPushButton(self.TabText)
        self.buttonTestSMTP.setGeometry(QtCore.QRect(520, 130, 88, 21))
        self.buttonTestSMTP.setObjectName("buttonTestSMTP")
        self.name = QtWidgets.QLineEdit(self.TabText)
        self.name.setGeometry(QtCore.QRect(460, 40, 211, 21))
        self.name.setText("")
        self.name.setClearButtonEnabled(True)
        self.name.setObjectName("name")
        self.server = QtWidgets.QLineEdit(self.TabText)
        self.server.setGeometry(QtCore.QRect(460, 10, 141, 21))
        self.server.setObjectName("server")
        self.port = QtWidgets.QLineEdit(self.TabText)
        self.port.setGeometry(QtCore.QRect(610, 10, 61, 21))
        self.port.setClearButtonEnabled(False)
        self.port.setObjectName("port")
        self.newEmail = QtWidgets.QLineEdit(self.TabText)
        self.newEmail.setGeometry(QtCore.QRect(10, 290, 651, 21))
        self.newEmail.setObjectName("newEmail")
        self.buttonTo = QtWidgets.QPushButton(self.TabText)
        self.buttonTo.setGeometry(QtCore.QRect(10, 320, 41, 21))
        self.buttonTo.setObjectName("buttonTo")
        self.listBcc = QtWidgets.QListWidget(self.TabText)
        self.listBcc.setGeometry(QtCore.QRect(430, 370, 201, 121))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listBcc.setFont(font)
        self.listBcc.setDragEnabled(True)
        self.listBcc.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listBcc.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listBcc.setObjectName("listBcc")
        self.listCc = QtWidgets.QListWidget(self.TabText)
        self.listCc.setGeometry(QtCore.QRect(220, 370, 201, 121))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listCc.setFont(font)
        self.listCc.setDragEnabled(True)
        self.listCc.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listCc.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listCc.setObjectName("listCc")
        self.listTo = QtWidgets.QListWidget(self.TabText)
        self.listTo.setGeometry(QtCore.QRect(10, 370, 201, 121))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listTo.setFont(font)
        self.listTo.setAutoFillBackground(True)
        self.listTo.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listTo.setDragEnabled(True)
        self.listTo.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listTo.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listTo.setObjectName("listTo")
        self.labelTo = QtWidgets.QLabel(self.TabText)
        self.labelTo.setGeometry(QtCore.QRect(10, 350, 58, 18))
        self.labelTo.setObjectName("labelTo")
        self.labelCc = QtWidgets.QLabel(self.TabText)
        self.labelCc.setGeometry(QtCore.QRect(220, 350, 58, 18))
        self.labelCc.setObjectName("labelCc")
        self.labelBcc = QtWidgets.QLabel(self.TabText)
        self.labelBcc.setGeometry(QtCore.QRect(430, 350, 58, 18))
        self.labelBcc.setObjectName("labelBcc")
        self.buttonCc = QtWidgets.QPushButton(self.TabText)
        self.buttonCc.setGeometry(QtCore.QRect(60, 320, 41, 21))
        self.buttonCc.setObjectName("buttonCc")
        self.buttonBcc = QtWidgets.QPushButton(self.TabText)
        self.buttonBcc.setGeometry(QtCore.QRect(110, 320, 41, 21))
        self.buttonBcc.setObjectName("buttonBcc")
        self.buttonRemove = QtWidgets.QPushButton(self.TabText)
        self.buttonRemove.setGeometry(QtCore.QRect(10, 500, 71, 21))
        self.buttonRemove.setObjectName("buttonRemove")
        self.buttonSend = QtWidgets.QPushButton(self.TabText)
        self.buttonSend.setGeometry(QtCore.QRect(530, 500, 101, 21))
        self.buttonSend.setObjectName("buttonSend")
        self.username.raise_()
        self.password.raise_()
        self.buttonTestSMTP.raise_()
        self.name.raise_()
        self.port.raise_()
        self.server.raise_()
        self.newEmail.raise_()
        self.buttonTo.raise_()
        self.listBcc.raise_()
        self.listCc.raise_()
        self.listTo.raise_()
        self.labelTo.raise_()
        self.labelCc.raise_()
        self.labelBcc.raise_()
        self.buttonCc.raise_()
        self.buttonBcc.raise_()
        self.buttonRemove.raise_()
        self.buttonSend.raise_()
        self.tabWidget.addTab(self.TabText, "")
        self.logView = QtWidgets.QTextBrowser(self.centralwidget)
        self.logView.setGeometry(QtCore.QRect(700, 30, 251, 541))
        self.logView.setObjectName("logView")
        self.labelLog = QtWidgets.QLabel(self.centralwidget)
        self.labelLog.setGeometry(QtCore.QRect(700, 10, 251, 18))
        self.labelLog.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLog.setObjectName("labelLog")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.textSubject)
        MainWindow.setTabOrder(self.textSubject, self.textMail)
        MainWindow.setTabOrder(self.textMail, self.newEmail)
        MainWindow.setTabOrder(self.newEmail, self.buttonTo)
        MainWindow.setTabOrder(self.buttonTo, self.buttonCc)
        MainWindow.setTabOrder(self.buttonCc, self.buttonBcc)
        MainWindow.setTabOrder(self.buttonBcc, self.server)
        MainWindow.setTabOrder(self.server, self.port)
        MainWindow.setTabOrder(self.port, self.name)
        MainWindow.setTabOrder(self.name, self.username)
        MainWindow.setTabOrder(self.username, self.password)
        MainWindow.setTabOrder(self.password, self.buttonTestSMTP)
        MainWindow.setTabOrder(self.buttonTestSMTP, self.listBcc)
        MainWindow.setTabOrder(self.listBcc, self.listCc)
        MainWindow.setTabOrder(self.listCc, self.listTo)
        MainWindow.setTabOrder(self.listTo, self.buttonRemove)
        MainWindow.setTabOrder(self.buttonRemove, self.logView)
        MainWindow.setTabOrder(self.logView, self.buttonSend)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mass Mailer"))
        self.textMail.setPlaceholderText(_translate("MainWindow", "Enter the mail text here..."))
        self.textSubject.setPlaceholderText(_translate("MainWindow", "Enter the subject here..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabProp), _translate("MainWindow", "Mail Text"))
        self.username.setPlaceholderText(_translate("MainWindow", "Enter the username."))
        self.password.setPlaceholderText(_translate("MainWindow", "Enter your password."))
        self.buttonTestSMTP.setText(_translate("MainWindow", "Test SMTP"))
        self.name.setPlaceholderText(_translate("MainWindow", "Enter the real name"))
        self.server.setText(_translate("MainWindow", "smtp.gmail.com"))
        self.server.setPlaceholderText(_translate("MainWindow", "SMTP server"))
        self.port.setText(_translate("MainWindow", "587"))
        self.port.setPlaceholderText(_translate("MainWindow", "Port"))
        self.newEmail.setPlaceholderText(_translate("MainWindow", "Add comma seperated emails."))
        self.buttonTo.setText(_translate("MainWindow", "To"))
        self.listTo.setSortingEnabled(False)
        self.labelTo.setText(_translate("MainWindow", "To:"))
        self.labelCc.setText(_translate("MainWindow", "Cc:"))
        self.labelBcc.setText(_translate("MainWindow", "Bcc:"))
        self.buttonCc.setText(_translate("MainWindow", "Cc"))
        self.buttonBcc.setText(_translate("MainWindow", "Bcc"))
        self.buttonRemove.setText(_translate("MainWindow", "Remove"))
        self.buttonSend.setText(_translate("MainWindow", "Send Emails"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabText), _translate("MainWindow", "Properties"))
        self.labelLog.setText(_translate("MainWindow", "System Log:"))

