# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mailer.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 731, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.TabProp = QtWidgets.QWidget()
        self.TabProp.setAccessibleName("")
        self.TabProp.setObjectName("TabProp")
        self.textMail = QtWidgets.QTextEdit(self.TabProp)
        self.textMail.setGeometry(QtCore.QRect(10, 40, 701, 431))
        self.textMail.setObjectName("textMail")
        self.textSubject = QtWidgets.QLineEdit(self.TabProp)
        self.textSubject.setGeometry(QtCore.QRect(10, 10, 701, 21))
        self.textSubject.setObjectName("textSubject")
        self.tabWidget.addTab(self.TabProp, "")
        self.TabText = QtWidgets.QWidget()
        self.TabText.setObjectName("TabText")
        self.buttonSend = QtWidgets.QPushButton(self.TabText)
        self.buttonSend.setGeometry(QtCore.QRect(540, 200, 91, 31))
        self.buttonSend.setObjectName("buttonSend")
        self.groupSMTP = QtWidgets.QGroupBox(self.TabText)
        self.groupSMTP.setGeometry(QtCore.QRect(480, 0, 231, 181))
        self.groupSMTP.setFlat(False)
        self.groupSMTP.setCheckable(False)
        self.groupSMTP.setObjectName("groupSMTP")
        self.buttonTestSMTP = QtWidgets.QPushButton(self.groupSMTP)
        self.buttonTestSMTP.setGeometry(QtCore.QRect(130, 150, 91, 21))
        self.buttonTestSMTP.setObjectName("buttonTestSMTP")
        self.port = QtWidgets.QLineEdit(self.groupSMTP)
        self.port.setGeometry(QtCore.QRect(160, 30, 61, 21))
        self.port.setClearButtonEnabled(False)
        self.port.setObjectName("port")
        self.server = QtWidgets.QLineEdit(self.groupSMTP)
        self.server.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.server.setObjectName("server")
        self.name = QtWidgets.QLineEdit(self.groupSMTP)
        self.name.setGeometry(QtCore.QRect(10, 60, 211, 21))
        self.name.setText("")
        self.name.setClearButtonEnabled(True)
        self.name.setObjectName("name")
        self.password = QtWidgets.QLineEdit(self.groupSMTP)
        self.password.setGeometry(QtCore.QRect(10, 120, 211, 21))
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.username = QtWidgets.QLineEdit(self.groupSMTP)
        self.username.setGeometry(QtCore.QRect(10, 90, 211, 21))
        self.username.setText("")
        self.username.setClearButtonEnabled(True)
        self.username.setObjectName("username")
        self.buttonTestSMTP.raise_()
        self.port.raise_()
        self.server.raise_()
        self.name.raise_()
        self.password.raise_()
        self.username.raise_()
        self.groupDestination = QtWidgets.QGroupBox(self.TabText)
        self.groupDestination.setGeometry(QtCore.QRect(340, 260, 381, 271))
        self.groupDestination.setObjectName("groupDestination")
        self.buttonTo = QtWidgets.QPushButton(self.groupDestination)
        self.buttonTo.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.buttonTo.setObjectName("buttonTo")
        self.newEmail = QtWidgets.QLineEdit(self.groupDestination)
        self.newEmail.setGeometry(QtCore.QRect(10, 30, 361, 21))
        self.newEmail.setObjectName("newEmail")
        self.buttonCc = QtWidgets.QPushButton(self.groupDestination)
        self.buttonCc.setGeometry(QtCore.QRect(50, 50, 41, 21))
        self.buttonCc.setObjectName("buttonCc")
        self.buttonBcc = QtWidgets.QPushButton(self.groupDestination)
        self.buttonBcc.setGeometry(QtCore.QRect(90, 50, 41, 21))
        self.buttonBcc.setObjectName("buttonBcc")
        self.buttonRemove = QtWidgets.QPushButton(self.groupDestination)
        self.buttonRemove.setGeometry(QtCore.QRect(130, 240, 121, 21))
        self.buttonRemove.setObjectName("buttonRemove")
        self.treeDestination = QtWidgets.QTreeWidget(self.groupDestination)
        self.treeDestination.setGeometry(QtCore.QRect(10, 70, 361, 161))
        self.treeDestination.setAutoScrollMargin(12)
        self.treeDestination.setAlternatingRowColors(True)
        self.treeDestination.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeDestination.setRootIsDecorated(False)
        self.treeDestination.setUniformRowHeights(True)
        self.treeDestination.setHeaderHidden(False)
        self.treeDestination.setColumnCount(3)
        self.treeDestination.setObjectName("treeDestination")
        self.treeDestination.header().setMinimumSectionSize(29)
        self.treeDestination.header().setSortIndicatorShown(True)
        self.groupSource = QtWidgets.QGroupBox(self.TabText)
        self.groupSource.setGeometry(QtCore.QRect(10, 0, 331, 531))
        self.groupSource.setObjectName("groupSource")
        self.buttonBcc_2 = QtWidgets.QPushButton(self.groupSource)
        self.buttonBcc_2.setGeometry(QtCore.QRect(210, 490, 41, 21))
        self.buttonBcc_2.setObjectName("buttonBcc_2")
        self.labelClass = QtWidgets.QLabel(self.groupSource)
        self.labelClass.setGeometry(QtCore.QRect(10, 70, 81, 18))
        self.labelClass.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClass.setObjectName("labelClass")
        self.buttonReadCharlemagne = QtWidgets.QPushButton(self.groupSource)
        self.buttonReadCharlemagne.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.buttonReadCharlemagne.setObjectName("buttonReadCharlemagne")
        self.buttonReadPersonnel = QtWidgets.QPushButton(self.groupSource)
        self.buttonReadPersonnel.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.buttonReadPersonnel.setObjectName("buttonReadPersonnel")
        self.labelClass_2 = QtWidgets.QLabel(self.groupSource)
        self.labelClass_2.setGeometry(QtCore.QRect(90, 70, 221, 18))
        self.labelClass_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClass_2.setObjectName("labelClass_2")
        self.buttonTo_2 = QtWidgets.QPushButton(self.groupSource)
        self.buttonTo_2.setGeometry(QtCore.QRect(130, 490, 41, 21))
        self.buttonTo_2.setObjectName("buttonTo_2")
        self.buttonCc_2 = QtWidgets.QPushButton(self.groupSource)
        self.buttonCc_2.setGeometry(QtCore.QRect(170, 490, 41, 21))
        self.buttonCc_2.setObjectName("buttonCc_2")
        self.listCategories = QtWidgets.QListWidget(self.groupSource)
        self.listCategories.setGeometry(QtCore.QRect(10, 90, 81, 401))
        self.listCategories.setAutoScrollMargin(12)
        self.listCategories.setObjectName("listCategories")
        self.treeSources = QtWidgets.QTreeWidget(self.groupSource)
        self.treeSources.setGeometry(QtCore.QRect(90, 90, 231, 401))
        self.treeSources.setAutoScrollMargin(12)
        self.treeSources.setAlternatingRowColors(True)
        self.treeSources.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeSources.setRootIsDecorated(False)
        self.treeSources.setUniformRowHeights(True)
        self.treeSources.setHeaderHidden(False)
        self.treeSources.setColumnCount(2)
        self.treeSources.setObjectName("treeSources")
        self.treeSources.header().setMinimumSectionSize(29)
        self.treeSources.header().setSortIndicatorShown(False)
        self.buttonBcc_2.raise_()
        self.labelClass.raise_()
        self.buttonReadCharlemagne.raise_()
        self.buttonReadPersonnel.raise_()
        self.labelClass_2.raise_()
        self.buttonTo_2.raise_()
        self.buttonCc_2.raise_()
        self.listCategories.raise_()
        self.buttonBcc_2.raise_()
        self.labelClass.raise_()
        self.buttonReadCharlemagne.raise_()
        self.buttonReadPersonnel.raise_()
        self.labelClass_2.raise_()
        self.buttonTo_2.raise_()
        self.buttonCc_2.raise_()
        self.listCategories.raise_()
        self.treeSources.raise_()
        self.buttonSend.raise_()
        self.groupSMTP.raise_()
        self.groupDestination.raise_()
        self.groupSource.raise_()
        self.tabWidget.addTab(self.TabText, "")
        self.logView = QtWidgets.QTextBrowser(self.centralwidget)
        self.logView.setGeometry(QtCore.QRect(730, 20, 221, 561))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.logView.setFont(font)
        self.logView.setAcceptRichText(False)
        self.logView.setObjectName("logView")
        self.labelLog = QtWidgets.QLabel(self.centralwidget)
        self.labelLog.setGeometry(QtCore.QRect(730, 0, 221, 20))
        self.labelLog.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLog.setObjectName("labelLog")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.textSubject)
        MainWindow.setTabOrder(self.textSubject, self.textMail)
        MainWindow.setTabOrder(self.textMail, self.newEmail)
        MainWindow.setTabOrder(self.newEmail, self.buttonTo)
        MainWindow.setTabOrder(self.buttonTo, self.buttonCc)
        MainWindow.setTabOrder(self.buttonCc, self.buttonBcc)
        MainWindow.setTabOrder(self.buttonBcc, self.server)
        MainWindow.setTabOrder(self.server, self.port)
        MainWindow.setTabOrder(self.port, self.name)
        MainWindow.setTabOrder(self.name, self.username)
        MainWindow.setTabOrder(self.username, self.password)
        MainWindow.setTabOrder(self.password, self.buttonTestSMTP)
        MainWindow.setTabOrder(self.buttonTestSMTP, self.buttonRemove)
        MainWindow.setTabOrder(self.buttonRemove, self.logView)
        MainWindow.setTabOrder(self.logView, self.buttonSend)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mass Mailer"))
        self.textMail.setPlaceholderText(_translate("MainWindow", "Enter the mail text here..."))
        self.textSubject.setPlaceholderText(_translate("MainWindow", "Enter the subject here..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabProp), _translate("MainWindow", "Mail Text"))
        self.buttonSend.setText(_translate("MainWindow", "Send Emails"))
        self.groupSMTP.setTitle(_translate("MainWindow", "SMTP Information"))
        self.buttonTestSMTP.setText(_translate("MainWindow", "Test SMTP"))
        self.port.setText(_translate("MainWindow", "587"))
        self.port.setPlaceholderText(_translate("MainWindow", "Port"))
        self.server.setText(_translate("MainWindow", "smtp.gmail.com"))
        self.server.setPlaceholderText(_translate("MainWindow", "SMTP server"))
        self.name.setPlaceholderText(_translate("MainWindow", "Enter the real name"))
        self.password.setPlaceholderText(_translate("MainWindow", "Enter your password."))
        self.username.setPlaceholderText(_translate("MainWindow", "Enter the username."))
        self.groupDestination.setTitle(_translate("MainWindow", "Destination"))
        self.buttonTo.setText(_translate("MainWindow", "To"))
        self.newEmail.setPlaceholderText(_translate("MainWindow", "Add comma seperated emails."))
        self.buttonCc.setText(_translate("MainWindow", "Cc"))
        self.buttonBcc.setText(_translate("MainWindow", "Bcc"))
        self.buttonRemove.setText(_translate("MainWindow", "Remove Selected"))
        self.treeDestination.setSortingEnabled(True)
        self.treeDestination.headerItem().setText(0, _translate("MainWindow", "Email"))
        self.treeDestination.headerItem().setText(1, _translate("MainWindow", "Name"))
        self.treeDestination.headerItem().setText(2, _translate("MainWindow", "Mode"))
        self.groupSource.setTitle(_translate("MainWindow", "Sources"))
        self.buttonBcc_2.setText(_translate("MainWindow", "Bcc"))
        self.labelClass.setText(_translate("MainWindow", "Categories"))
        self.buttonReadCharlemagne.setText(_translate("MainWindow", "Charlemagne"))
        self.buttonReadPersonnel.setText(_translate("MainWindow", "Personnel"))
        self.labelClass_2.setText(_translate("MainWindow", "Emails"))
        self.buttonTo_2.setText(_translate("MainWindow", "To"))
        self.buttonCc_2.setText(_translate("MainWindow", "Cc"))
        self.treeSources.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.treeSources.headerItem().setText(1, _translate("MainWindow", "Email"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabText), _translate("MainWindow", "Properties"))
        self.labelLog.setText(_translate("MainWindow", "System Log:"))

